apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: termination-demo
  name: termination-demo
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 10 && echo "sleep expired" > /dev/termination-log
    image: debian
    name: termination-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
