apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: sleepy01
spec:
  completions: 5
  parallelism: 2
  activeDeadlineSeconds: 15
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: sleepy01
        command: ["/bin/sleep"]
        args: ["3"]
        resources: {}
      restartPolicy: Never
status: {}
