apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"	
      readOnly: true
    resources: {}
  volumes:
  - name: foo
    secret:
      secretName: mysecret2
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
