apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
           name: mysecret
           key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
