apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2019-04-06T10:27:06Z
  labels:
    run: busybox
  name: busybox
  namespace: mynamespace
  resourceVersion: "1226674"
  selfLink: /api/v1/namespaces/mynamespace/pods/busybox
  uid: 8704adf8-5856-11e9-99f4-0800271479c7
spec:
  containers:
  - command:
    - env
    image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-9llr5
      readOnly: true
  dnsPolicy: ClusterFirst
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-9llr5
    secret:
      defaultMode: 420
      secretName: default-token-9llr5
status:
  phase: Pending
  qosClass: BestEffort
