apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fruit-service
  name: fruit-service
spec:
  volumes:
  - name: config-volume
    configMap:
      name:  fruit-service-ambassador-config
  containers:
  - name: legacy-fruit-service
    image: linuxacademycontent/legacy-fruit-service:1
  - image: haproxy:1.7
    name: haproxy-ambassador
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /usr/local/etc/haproxy
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
