apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: security-context-demo-3
spec:
  containers:
  - image: gcr.io/google-samples/node-hello:1.0 
    name: sec-ctx-demo-3
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
