apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: security-context-demo-2 
spec:
  containers:
  - image: gcr.io/google-samples/node-hello:1.0 
    name: sec-ctx-demo-2
    securityContext:
      runAsUser: 2000    
      allowPrivilegeEscalation: false
    resources: {}
  securityContext:
    runAsUser: 1000
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
